In [ ]:
print("hello world")


hello world


In [8]:
import numpy as np

In [9]:
print(np.__version__)

1.22.4


In [ ]:
np.array([0,0,0,0,0,0,0,0,0,0])

In [15]:
a = np.array([0,0,0,0,0,0,0,0,0,0])
a.size
a.shape

(10,)

In [16]:
np.array([0]*10)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [29]:
a = np.arange(10)

In [30]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
b = np.arange(10,50)
b

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [33]:
b >= 20

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True])

In [40]:
c = np.array([
[1,1],
    [1,1]
])
c.shape

(2, 2)

In [12]:
import numpy as np
x = np.arange(4)
np.arange(4, dtype=np.float)
np.ones_like(x)

<ipython-input-12-670e98facb68>:3: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.arange(4, dtype=np.float)


array([1, 1, 1, 1])

In [16]:
x = np.array([[1,2,3], [4,5,6]], dtype=int)
np.zeros_like(x)

array([[0, 0, 0],
       [0, 0, 0]])

In [17]:
np.ones([4,4], dtype=int)* 5

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [18]:
a = np.array([[1,2], [6,2]], dtype=int)
np.ones_like(a)* 7

array([[7, 7],
       [7, 7]])

In [19]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
np.random.randint(10, size=3)

array([7, 6, 2])

In [26]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [1]:
import numpy as np
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [7]:
np.random.random(size=2)
np.random.normal(size=2)
np.random.rand(2,4)
np.arange(10)
np.arange(0,1,.1)
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [11]:
np.identity(3)
np.eye(3,3)
np.eye(8,4, k=-3)
np.empty(5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [2]:
import numpy as np
import pandas as pd
print(pd.__version__)

1.5.3


In [4]:
X = ['A','B','C']
print(X)
Y = pd.Series(X)

['A', 'B', 'C']


In [6]:
Y.name = 'My Letters'
Y

0    A
1    B
2    C
Name: My Letters, dtype: object

In [8]:
Y.dtype
Y.values

array(['A', 'B', 'C'], dtype=object)

In [10]:
Y.index = ['Aliu','Akeem','Oluwaseyi']
Y

Aliu         A
Akeem        B
Oluwaseyi    C
Name: My Letters, dtype: object

In [14]:
Y.iloc[0]
Y.loc['Oluwaseyi']

'C'

In [16]:
x = pd.Series(['A','B','C','D','E'], index = ['Aliu','Akeem','Oluwaseyi','August','Adesanya'], name = 'Rubbish List i am compiling')
x

Aliu         A
Akeem        B
Oluwaseyi    C
August       D
Adesanya     E
Name: Rubbish List i am compiling, dtype: object

In [17]:
x.iloc[1:-1]

Akeem        B
Oluwaseyi    C
August       D
Name: Rubbish List i am compiling, dtype: object

In [18]:
x.iloc[::-1]

Adesanya     E
August       D
Oluwaseyi    C
Akeem        B
Aliu         A
Name: Rubbish List i am compiling, dtype: object

In [30]:
x[['Aliu','Adesanya']]
x[[0,-1]]
x.iloc[[0,-1]]

Aliu        A
Adesanya    E
Name: Rubbish List i am compiling, dtype: object

In [32]:
a = pd.Series([1,2,3,4,5], index = ['Aliu','Akeem','August','Adesanya','Oluwaseyi'], name = 'Rubbish list')
a

Aliu         1
Akeem        2
August       3
Adesanya     4
Oluwaseyi    5
Name: Rubbish list, dtype: int64

In [33]:
pd.Series(a, dtype=np.float)

<ipython-input-33-d1d237e55b4b>:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  pd.Series(a, dtype=np.float)


Aliu         1.0
Akeem        2.0
August       3.0
Adesanya     4.0
Oluwaseyi    5.0
Name: Rubbish list, dtype: float64

In [35]:
a[-1] = 10
a

Aliu          1
Akeem         2
August        3
Adesanya      4
Oluwaseyi    10
Name: Rubbish list, dtype: int64

In [41]:
a[1:-1] = 0
a

Aliu          1
Akeem         0
August        0
Adesanya      0
Oluwaseyi    10
Name: Rubbish list, dtype: int64

In [45]:
a+5
a

Aliu         11
Akeem        10
August       10
Adesanya     10
Oluwaseyi    20
Name: Rubbish list, dtype: int64

In [46]:
o = pd.Series([-1,2,0,-4,5,6,0,0,-9,10])
o <= 0

0     True
1    False
2     True
3     True
4    False
5    False
6     True
7     True
8     True
9    False
dtype: bool

In [47]:
o[o <= 0]

0   -1
2    0
3   -4
6    0
7    0
8   -9
dtype: int64

In [51]:
w = pd.Series([0,2,-3,4,-5,1,-6,7,-8,9,10])
w.all()
w.any()
w.describe()

count    11.000000
mean      1.000000
std       6.115554
min      -8.000000
25%      -4.000000
50%       1.000000
75%       5.500000
max      10.000000
dtype: float64

In [52]:
w.sum()

11

In [53]:
w.mean()

1.0

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
ecowasa7_pop = pd.Series([521,1991,12609,1844,4503,17600,15129])
ecowasa7_pop

0      521
1     1991
2    12609
3     1844
4     4503
5    17600
6    15129
dtype: int64

In [3]:
ecowasa7_pop.name = 'ECOWAS A7 population in thoousands'
ecowasa7_pop

0      521
1     1991
2    12609
3     1844
4     4503
5    17600
6    15129
Name: ECOWAS A7 population in thoousands, dtype: int64

In [4]:
ecowasa7_pop.dtype

dtype('int64')

In [5]:
ecowasa7_pop.index = ['Cape Verde','Gambia','Guinea','Guinea-Bissau','Liberia','Mali','Senegal']
ecowasa7_pop

Cape Verde         521
Gambia            1991
Guinea           12609
Guinea-Bissau     1844
Liberia           4503
Mali             17600
Senegal          15129
Name: ECOWAS A7 population in thoousands, dtype: int64

In [18]:
ecowasa7_pop['Cape Verde']
ecowasa7_pop.loc['Senegal']
ecowasa7_pop.iloc[1]
ecowasa7_pop>1500
ecowasa7_pop[ecowasa7_pop>1500]
ecowasa7_pop.describe()
ecowasa7_pop* 1000
ecowasa7_pop['Guinea'] = 600
ecowasa7_pop

Cape Verde         521
Gambia            1991
Guinea             600
Guinea-Bissau     1844
Liberia           4503
Mali             17600
Senegal          15129
Name: ECOWAS A7 population in thoousands, dtype: int64

In [19]:
df = pd.DataFrame({'Area(Km)': [4033,11295,245875,36125,111369,1240192,196712],
                   'Population': [521,1991,12609,1844,4503,17600,15129],
                   'GDP': [1603,939,6699,1057,2053,12747,13510],
                   'Currency': ['escudo','dalasi','franc','CFA franc','dollar','CFA franc','CFA franc'],
                   'Official Language': ['Portuguese','English','French','Portuguese','English','French','French']},
                  columns = ['Area(Km)','Population','GDP','Currency','Official Language'])
df

Area(Km)  Population    GDP   Currency Official Language
0      4033         521   1603     escudo        Portuguese
1     11295        1991    939     dalasi           English
2    245875       12609   6699      franc            French
3     36125        1844   1057  CFA franc        Portuguese
4    111369        4503   2053     dollar           English
5   1240192       17600  12747  CFA franc            French
6    196712       15129  13510  CFA franc            French

In [22]:
df.index = ['Cape Verde','Gambia','Guinea','Guinea-Bissau','Liberia','Mali','Senegal']
df

Area(Km)  Population    GDP   Currency Official Language
Cape Verde         4033         521   1603     escudo        Portuguese
Gambia            11295        1991    939     dalasi           English
Guinea           245875       12609   6699      franc            French
Guinea-Bissau     36125        1844   1057  CFA franc        Portuguese
Liberia          111369        4503   2053     dollar           English
Mali            1240192       17600  12747  CFA franc            French
Senegal          196712       15129  13510  CFA franc            French

In [24]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
Index: 7 entries, Cape Verde to Senegal
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype 
---  ------             --------------  ----- 
 0   Area(Km)           7 non-null      int64 
 1   Population         7 non-null      int64 
 2   GDP                7 non-null      int64 
 3   Currency           7 non-null      object
 4   Official Language  7 non-null      object
dtypes: int64(3), object(2)
memory usage: 336.0+ bytes


35